//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoCal">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RutDistribuidor" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="TipoCertificado">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="C"/>
 *                         &lt;enumeration value="P"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Clase">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TipoLCE">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="PeriodoVigencia" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *                   &lt;element name="TmstFirma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoCal",
    "signature"
})
@XmlRootElement(name = "LceCal")
public class LceCal {

    @XmlElement(name = "DocumentoCal", required = true)
    protected LceCal.DocumentoCal documentoCal;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the documentoCal property.
     * 
     * @return
     *     possible object is
     *     {@link LceCal.DocumentoCal }
     *     
     */
    public LceCal.DocumentoCal getDocumentoCal() {
        return documentoCal;
    }

    /**
     * Sets the value of the documentoCal property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceCal.DocumentoCal }
     *     
     */
    public void setDocumentoCal(LceCal.DocumentoCal value) {
        this.documentoCal = value;
    }

    /**
     * Firma Digital sobre Documento
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RutDistribuidor" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="TipoCertificado">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="C"/>
     *               &lt;enumeration value="P"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Clase">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TipoLCE">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="PeriodoVigencia" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
     *         &lt;element name="TmstFirma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rutDistribuidor",
        "tipoCertificado",
        "clase",
        "tipoLCE",
        "fchEmision",
        "periodoVigencia",
        "tmstFirma"
    })
    public static class DocumentoCal {

        @XmlElement(name = "RutDistribuidor", required = true)
        protected String rutDistribuidor;
        @XmlElement(name = "TipoCertificado", required = true)
        protected String tipoCertificado;
        @XmlElement(name = "Clase", required = true)
        protected String clase;
        @XmlElement(name = "TipoLCE", required = true)
        protected BigInteger tipoLCE;
        @XmlElement(name = "FchEmision", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fchEmision;
        @XmlElement(name = "PeriodoVigencia", required = true)
        @XmlSchemaType(name = "gYear")
        protected XMLGregorianCalendar periodoVigencia;
        @XmlElement(name = "TmstFirma", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar tmstFirma;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the rutDistribuidor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutDistribuidor() {
            return rutDistribuidor;
        }

        /**
         * Sets the value of the rutDistribuidor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutDistribuidor(String value) {
            this.rutDistribuidor = value;
        }

        /**
         * Gets the value of the tipoCertificado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoCertificado() {
            return tipoCertificado;
        }

        /**
         * Sets the value of the tipoCertificado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoCertificado(String value) {
            this.tipoCertificado = value;
        }

        /**
         * Gets the value of the clase property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClase() {
            return clase;
        }

        /**
         * Sets the value of the clase property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClase(String value) {
            this.clase = value;
        }

        /**
         * Gets the value of the tipoLCE property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTipoLCE() {
            return tipoLCE;
        }

        /**
         * Sets the value of the tipoLCE property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTipoLCE(BigInteger value) {
            this.tipoLCE = value;
        }

        /**
         * Gets the value of the fchEmision property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFchEmision() {
            return fchEmision;
        }

        /**
         * Sets the value of the fchEmision property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFchEmision(XMLGregorianCalendar value) {
            this.fchEmision = value;
        }

        /**
         * Gets the value of the periodoVigencia property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getPeriodoVigencia() {
            return periodoVigencia;
        }

        /**
         * Sets the value of the periodoVigencia property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setPeriodoVigencia(XMLGregorianCalendar value) {
            this.periodoVigencia = value;
        }

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }

}
