//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoCoCertif">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element ref="{http://www.sii.cl/SiiLce}LceCal"/>
 *                   &lt;element name="RutFirmanteDistribuidor" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="TmstFirma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoCoCertif",
    "signature"
})
@XmlRootElement(name = "LceCoCertif")
public class LceCoCertif {

    @XmlElement(name = "DocumentoCoCertif", required = true)
    protected LceCoCertif.DocumentoCoCertif documentoCoCertif;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the documentoCoCertif property.
     * 
     * @return
     *     possible object is
     *     {@link LceCoCertif.DocumentoCoCertif }
     *     
     */
    public LceCoCertif.DocumentoCoCertif getDocumentoCoCertif() {
        return documentoCoCertif;
    }

    /**
     * Sets the value of the documentoCoCertif property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceCoCertif.DocumentoCoCertif }
     *     
     */
    public void setDocumentoCoCertif(LceCoCertif.DocumentoCoCertif value) {
        this.documentoCoCertif = value;
    }

    /**
     * Firma Digital sobre Documento
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element ref="{http://www.sii.cl/SiiLce}LceCal"/>
     *         &lt;element name="RutFirmanteDistribuidor" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="TmstFirma" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rutContribuyente",
        "fchEmision",
        "lceCal",
        "rutFirmanteDistribuidor",
        "tmstFirma"
    })
    public static class DocumentoCoCertif {

        @XmlElement(name = "RutContribuyente", required = true)
        protected String rutContribuyente;
        @XmlElement(name = "FchEmision", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fchEmision;
        @XmlElement(name = "LceCal", required = true)
        protected LceCal lceCal;
        @XmlElement(name = "RutFirmanteDistribuidor", required = true)
        protected String rutFirmanteDistribuidor;
        @XmlElement(name = "TmstFirma", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar tmstFirma;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the rutContribuyente property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutContribuyente() {
            return rutContribuyente;
        }

        /**
         * Sets the value of the rutContribuyente property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutContribuyente(String value) {
            this.rutContribuyente = value;
        }

        /**
         * Gets the value of the fchEmision property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFchEmision() {
            return fchEmision;
        }

        /**
         * Sets the value of the fchEmision property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFchEmision(XMLGregorianCalendar value) {
            this.fchEmision = value;
        }

        /**
         * Gets the value of the lceCal property.
         * 
         * @return
         *     possible object is
         *     {@link LceCal }
         *     
         */
        public LceCal getLceCal() {
            return lceCal;
        }

        /**
         * Sets the value of the lceCal property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceCal }
         *     
         */
        public void setLceCal(LceCal value) {
            this.lceCal = value;
        }

        /**
         * Gets the value of the rutFirmanteDistribuidor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutFirmanteDistribuidor() {
            return rutFirmanteDistribuidor;
        }

        /**
         * Sets the value of the rutFirmanteDistribuidor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutFirmanteDistribuidor(String value) {
            this.rutFirmanteDistribuidor = value;
        }

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }

    }

}
