//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoDiarioRes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Identificacion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                             &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
 *                             &lt;element name="Moneda" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RegistroDiario" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="CantidadComprobantes">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                                   &lt;totalDigits value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CantidadMovimientos">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                                   &lt;totalDigits value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Cierre">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CantidadComprobantes">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                                   &lt;totalDigits value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CantidadMovimientos">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                                   &lt;totalDigits value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                             &lt;element name="ValorAcumulado" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="TmstFirma">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoDiarioRes",
    "signature"
})
@XmlRootElement(name = "LceDiarioRes")
public class LceDiarioRes {

    @XmlElement(name = "DocumentoDiarioRes", required = true)
    protected LceDiarioRes.DocumentoDiarioRes documentoDiarioRes;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the documentoDiarioRes property.
     * 
     * @return
     *     possible object is
     *     {@link LceDiarioRes.DocumentoDiarioRes }
     *     
     */
    public LceDiarioRes.DocumentoDiarioRes getDocumentoDiarioRes() {
        return documentoDiarioRes;
    }

    /**
     * Sets the value of the documentoDiarioRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceDiarioRes.DocumentoDiarioRes }
     *     
     */
    public void setDocumentoDiarioRes(LceDiarioRes.DocumentoDiarioRes value) {
        this.documentoDiarioRes = value;
    }

    /**
     * Firma Digital del Envio del Libro Electronico
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Identificacion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *                   &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
     *                   &lt;element name="Moneda" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RegistroDiario" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="CantidadComprobantes">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *                         &lt;totalDigits value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CantidadMovimientos">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *                         &lt;totalDigits value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Cierre">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CantidadComprobantes">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *                         &lt;totalDigits value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CantidadMovimientos">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *                         &lt;totalDigits value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                   &lt;element name="ValorAcumulado" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="TmstFirma">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificacion",
        "registroDiario",
        "cierre",
        "rutFirma",
        "tmstFirma"
    })
    public static class DocumentoDiarioRes {

        @XmlElement(name = "Identificacion", required = true)
        protected LceDiarioRes.DocumentoDiarioRes.Identificacion identificacion;
        @XmlElement(name = "RegistroDiario")
        protected List<LceDiarioRes.DocumentoDiarioRes.RegistroDiario> registroDiario;
        @XmlElement(name = "Cierre", required = true)
        protected LceDiarioRes.DocumentoDiarioRes.Cierre cierre;
        @XmlElement(name = "RutFirma", required = true)
        protected String rutFirma;
        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the identificacion property.
         * 
         * @return
         *     possible object is
         *     {@link LceDiarioRes.DocumentoDiarioRes.Identificacion }
         *     
         */
        public LceDiarioRes.DocumentoDiarioRes.Identificacion getIdentificacion() {
            return identificacion;
        }

        /**
         * Sets the value of the identificacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceDiarioRes.DocumentoDiarioRes.Identificacion }
         *     
         */
        public void setIdentificacion(LceDiarioRes.DocumentoDiarioRes.Identificacion value) {
            this.identificacion = value;
        }

        /**
         * Gets the value of the registroDiario property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the registroDiario property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRegistroDiario().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LceDiarioRes.DocumentoDiarioRes.RegistroDiario }
         * 
         * 
         */
        public List<LceDiarioRes.DocumentoDiarioRes.RegistroDiario> getRegistroDiario() {
            if (registroDiario == null) {
                registroDiario = new ArrayList<LceDiarioRes.DocumentoDiarioRes.RegistroDiario>();
            }
            return this.registroDiario;
        }

        /**
         * Gets the value of the cierre property.
         * 
         * @return
         *     possible object is
         *     {@link LceDiarioRes.DocumentoDiarioRes.Cierre }
         *     
         */
        public LceDiarioRes.DocumentoDiarioRes.Cierre getCierre() {
            return cierre;
        }

        /**
         * Sets the value of the cierre property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceDiarioRes.DocumentoDiarioRes.Cierre }
         *     
         */
        public void setCierre(LceDiarioRes.DocumentoDiarioRes.Cierre value) {
            this.cierre = value;
        }

        /**
         * Gets the value of the rutFirma property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutFirma() {
            return rutFirma;
        }

        /**
         * Sets the value of the rutFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutFirma(String value) {
            this.rutFirma = value;
        }

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CantidadComprobantes">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
         *               &lt;totalDigits value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CantidadMovimientos">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
         *               &lt;totalDigits value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *         &lt;element name="ValorAcumulado" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cantidadComprobantes",
            "cantidadMovimientos",
            "sumaValorComprobante",
            "valorAcumulado"
        })
        public static class Cierre {

            @XmlElement(name = "CantidadComprobantes", required = true)
            protected BigInteger cantidadComprobantes;
            @XmlElement(name = "CantidadMovimientos", required = true)
            protected BigInteger cantidadMovimientos;
            @XmlElement(name = "SumaValorComprobante", required = true)
            protected BigDecimal sumaValorComprobante;
            @XmlElement(name = "ValorAcumulado", required = true)
            protected BigDecimal valorAcumulado;

            /**
             * Gets the value of the cantidadComprobantes property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCantidadComprobantes() {
                return cantidadComprobantes;
            }

            /**
             * Sets the value of the cantidadComprobantes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCantidadComprobantes(BigInteger value) {
                this.cantidadComprobantes = value;
            }

            /**
             * Gets the value of the cantidadMovimientos property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCantidadMovimientos() {
                return cantidadMovimientos;
            }

            /**
             * Sets the value of the cantidadMovimientos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCantidadMovimientos(BigInteger value) {
                this.cantidadMovimientos = value;
            }

            /**
             * Gets the value of the sumaValorComprobante property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSumaValorComprobante() {
                return sumaValorComprobante;
            }

            /**
             * Sets the value of the sumaValorComprobante property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSumaValorComprobante(BigDecimal value) {
                this.sumaValorComprobante = value;
            }

            /**
             * Gets the value of the valorAcumulado property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValorAcumulado() {
                return valorAcumulado;
            }

            /**
             * Sets the value of the valorAcumulado property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValorAcumulado(BigDecimal value) {
                this.valorAcumulado = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
         *         &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
         *         &lt;element name="Moneda" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rutContribuyente",
            "periodoTributario",
            "moneda",
            "rectificatoria"
        })
        public static class Identificacion {

            @XmlElement(name = "RutContribuyente", required = true)
            protected String rutContribuyente;
            @XmlElement(name = "PeriodoTributario", required = true)
            protected Periodo periodoTributario;
            @XmlElement(name = "Moneda")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String moneda;
            @XmlElement(name = "Rectificatoria")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger rectificatoria;

            /**
             * Gets the value of the rutContribuyente property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRutContribuyente() {
                return rutContribuyente;
            }

            /**
             * Sets the value of the rutContribuyente property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRutContribuyente(String value) {
                this.rutContribuyente = value;
            }

            /**
             * Gets the value of the periodoTributario property.
             * 
             * @return
             *     possible object is
             *     {@link Periodo }
             *     
             */
            public Periodo getPeriodoTributario() {
                return periodoTributario;
            }

            /**
             * Sets the value of the periodoTributario property.
             * 
             * @param value
             *     allowed object is
             *     {@link Periodo }
             *     
             */
            public void setPeriodoTributario(Periodo value) {
                this.periodoTributario = value;
            }

            /**
             * Gets the value of the moneda property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMoneda() {
                return moneda;
            }

            /**
             * Sets the value of the moneda property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMoneda(String value) {
                this.moneda = value;
            }

            /**
             * Gets the value of the rectificatoria property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRectificatoria() {
                return rectificatoria;
            }

            /**
             * Sets the value of the rectificatoria property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRectificatoria(BigInteger value) {
                this.rectificatoria = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="CantidadComprobantes">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
         *               &lt;totalDigits value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CantidadMovimientos">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
         *               &lt;totalDigits value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="SumaValorComprobante" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fechaContable",
            "cantidadComprobantes",
            "cantidadMovimientos",
            "sumaValorComprobante"
        })
        public static class RegistroDiario {

            @XmlElement(name = "FechaContable", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaContable;
            @XmlElement(name = "CantidadComprobantes", required = true)
            protected BigInteger cantidadComprobantes;
            @XmlElement(name = "CantidadMovimientos", required = true)
            protected BigInteger cantidadMovimientos;
            @XmlElement(name = "SumaValorComprobante", required = true)
            protected BigDecimal sumaValorComprobante;

            /**
             * Gets the value of the fechaContable property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaContable() {
                return fechaContable;
            }

            /**
             * Sets the value of the fechaContable property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaContable(XMLGregorianCalendar value) {
                this.fechaContable = value;
            }

            /**
             * Gets the value of the cantidadComprobantes property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCantidadComprobantes() {
                return cantidadComprobantes;
            }

            /**
             * Sets the value of the cantidadComprobantes property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCantidadComprobantes(BigInteger value) {
                this.cantidadComprobantes = value;
            }

            /**
             * Gets the value of the cantidadMovimientos property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCantidadMovimientos() {
                return cantidadMovimientos;
            }

            /**
             * Sets the value of the cantidadMovimientos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCantidadMovimientos(BigInteger value) {
                this.cantidadMovimientos = value;
            }

            /**
             * Gets the value of the sumaValorComprobante property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSumaValorComprobante() {
                return sumaValorComprobante;
            }

            /**
             * Sets the value of the sumaValorComprobante property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSumaValorComprobante(BigDecimal value) {
                this.sumaValorComprobante = value;
            }

        }

    }

}
