//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoDiccionario">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Identificacion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                             &lt;element name="PeriodoTributario" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
 *                             &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Cuenta" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ClasificacionCuenta">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="1"/>
 *                                   &lt;enumeration value="2"/>
 *                                   &lt;enumeration value="3"/>
 *                                   &lt;enumeration value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodigoCuenta">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Glosa">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="40"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CodigoSII">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="16"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="TmstFirma">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoDiccionario",
    "signature"
})
@XmlRootElement(name = "LceDiccionario")
public class LceDiccionario {

    @XmlElement(name = "DocumentoDiccionario", required = true)
    protected LceDiccionario.DocumentoDiccionario documentoDiccionario;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the documentoDiccionario property.
     * 
     * @return
     *     possible object is
     *     {@link LceDiccionario.DocumentoDiccionario }
     *     
     */
    public LceDiccionario.DocumentoDiccionario getDocumentoDiccionario() {
        return documentoDiccionario;
    }

    /**
     * Sets the value of the documentoDiccionario property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceDiccionario.DocumentoDiccionario }
     *     
     */
    public void setDocumentoDiccionario(LceDiccionario.DocumentoDiccionario value) {
        this.documentoDiccionario = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Identificacion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *                   &lt;element name="PeriodoTributario" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
     *                   &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Cuenta" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ClasificacionCuenta">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="1"/>
     *                         &lt;enumeration value="2"/>
     *                         &lt;enumeration value="3"/>
     *                         &lt;enumeration value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodigoCuenta">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Glosa">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="40"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CodigoSII">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="16"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="TmstFirma">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificacion",
        "cuenta",
        "rutFirma",
        "tmstFirma"
    })
    public static class DocumentoDiccionario {

        @XmlElement(name = "Identificacion", required = true)
        protected LceDiccionario.DocumentoDiccionario.Identificacion identificacion;
        @XmlElement(name = "Cuenta")
        protected List<LceDiccionario.DocumentoDiccionario.Cuenta> cuenta;
        @XmlElement(name = "RutFirma", required = true)
        protected String rutFirma;
        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the identificacion property.
         * 
         * @return
         *     possible object is
         *     {@link LceDiccionario.DocumentoDiccionario.Identificacion }
         *     
         */
        public LceDiccionario.DocumentoDiccionario.Identificacion getIdentificacion() {
            return identificacion;
        }

        /**
         * Sets the value of the identificacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceDiccionario.DocumentoDiccionario.Identificacion }
         *     
         */
        public void setIdentificacion(LceDiccionario.DocumentoDiccionario.Identificacion value) {
            this.identificacion = value;
        }

        /**
         * Gets the value of the cuenta property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cuenta property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCuenta().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LceDiccionario.DocumentoDiccionario.Cuenta }
         * 
         * 
         */
        public List<LceDiccionario.DocumentoDiccionario.Cuenta> getCuenta() {
            if (cuenta == null) {
                cuenta = new ArrayList<LceDiccionario.DocumentoDiccionario.Cuenta>();
            }
            return this.cuenta;
        }

        /**
         * Gets the value of the rutFirma property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutFirma() {
            return rutFirma;
        }

        /**
         * Sets the value of the rutFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutFirma(String value) {
            this.rutFirma = value;
        }

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ClasificacionCuenta">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="1"/>
         *               &lt;enumeration value="2"/>
         *               &lt;enumeration value="3"/>
         *               &lt;enumeration value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodigoCuenta">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Glosa">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="40"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CodigoSII">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="16"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "clasificacionCuenta",
            "codigoCuenta",
            "glosa",
            "codigoSII"
        })
        public static class Cuenta {

            @XmlElement(name = "ClasificacionCuenta", required = true)
            protected String clasificacionCuenta;
            @XmlElement(name = "CodigoCuenta", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String codigoCuenta;
            @XmlElement(name = "Glosa", required = true)
            protected String glosa;
            @XmlElement(name = "CodigoSII", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String codigoSII;

            /**
             * Gets the value of the clasificacionCuenta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClasificacionCuenta() {
                return clasificacionCuenta;
            }

            /**
             * Sets the value of the clasificacionCuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClasificacionCuenta(String value) {
                this.clasificacionCuenta = value;
            }

            /**
             * Gets the value of the codigoCuenta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigoCuenta() {
                return codigoCuenta;
            }

            /**
             * Sets the value of the codigoCuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigoCuenta(String value) {
                this.codigoCuenta = value;
            }

            /**
             * Gets the value of the glosa property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGlosa() {
                return glosa;
            }

            /**
             * Sets the value of the glosa property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGlosa(String value) {
                this.glosa = value;
            }

            /**
             * Gets the value of the codigoSII property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigoSII() {
                return codigoSII;
            }

            /**
             * Sets the value of the codigoSII property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigoSII(String value) {
                this.codigoSII = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
         *         &lt;element name="PeriodoTributario" type="{http://www.w3.org/2001/XMLSchema}gYear"/>
         *         &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rutContribuyente",
            "periodoTributario",
            "rectificatoria"
        })
        public static class Identificacion {

            @XmlElement(name = "RutContribuyente", required = true)
            protected String rutContribuyente;
            @XmlElement(name = "PeriodoTributario", required = true)
            @XmlSchemaType(name = "gYear")
            protected XMLGregorianCalendar periodoTributario;
            @XmlElement(name = "Rectificatoria")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger rectificatoria;

            /**
             * Gets the value of the rutContribuyente property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRutContribuyente() {
                return rutContribuyente;
            }

            /**
             * Sets the value of the rutContribuyente property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRutContribuyente(String value) {
                this.rutContribuyente = value;
            }

            /**
             * Gets the value of the periodoTributario property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getPeriodoTributario() {
                return periodoTributario;
            }

            /**
             * Sets the value of the periodoTributario property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setPeriodoTributario(XMLGregorianCalendar value) {
                this.periodoTributario = value;
            }

            /**
             * Gets the value of the rectificatoria property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRectificatoria() {
                return rectificatoria;
            }

            /**
             * Sets the value of the rectificatoria property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRectificatoria(BigInteger value) {
                this.rectificatoria = value;
            }

        }

    }

}
