//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.sii.cl/SiiLce}LceMayorRes"/>
 *         &lt;element name="Cuenta" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CodigoCuenta">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="20"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Apertura" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                             &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                             &lt;choice>
 *                               &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                               &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Movimientos" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="TpoComp">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;maxLength value="4"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="NumComp">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="18"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="GlosaAnalisis" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="120"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Rut" type="{http://www.sii.cl/SiiLce}RUTType" minOccurs="0"/>
 *                             &lt;element name="Nombre" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="120"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="TpoDocum" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;maxLength value="15"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Numero" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;maxLength value="18"/>
 *                                   &lt;minLength value="1"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="FchVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                             &lt;element name="GlosaRef" maxOccurs="4" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Glosa">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="30"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                       &lt;element name="Ref">
 *                                         &lt;simpleType>
 *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                             &lt;maxLength value="20"/>
 *                                           &lt;/restriction>
 *                                         &lt;/simpleType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;choice>
 *                               &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                               &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                             &lt;/choice>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lceMayorRes",
    "cuenta"
})
@XmlRootElement(name = "LceMayor")
public class LceMayor {

    @XmlElement(name = "LceMayorRes", required = true)
    protected LceMayorRes lceMayorRes;
    @XmlElement(name = "Cuenta", required = true)
    protected List<LceMayor.Cuenta> cuenta;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the lceMayorRes property.
     * 
     * @return
     *     possible object is
     *     {@link LceMayorRes }
     *     
     */
    public LceMayorRes getLceMayorRes() {
        return lceMayorRes;
    }

    /**
     * Sets the value of the lceMayorRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceMayorRes }
     *     
     */
    public void setLceMayorRes(LceMayorRes value) {
        this.lceMayorRes = value;
    }

    /**
     * Gets the value of the cuenta property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cuenta property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCuenta().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LceMayor.Cuenta }
     * 
     * 
     */
    public List<LceMayor.Cuenta> getCuenta() {
        if (cuenta == null) {
            cuenta = new ArrayList<LceMayor.Cuenta>();
        }
        return this.cuenta;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CodigoCuenta">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="20"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Apertura" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                   &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                   &lt;choice>
     *                     &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                     &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Movimientos" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TpoComp">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;maxLength value="4"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="NumComp">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="18"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="GlosaAnalisis" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="120"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Rut" type="{http://www.sii.cl/SiiLce}RUTType" minOccurs="0"/>
     *                   &lt;element name="Nombre" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="120"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="TpoDocum" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;maxLength value="15"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Numero" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;maxLength value="18"/>
     *                         &lt;minLength value="1"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="FchVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *                   &lt;element name="GlosaRef" maxOccurs="4" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Glosa">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="30"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                             &lt;element name="Ref">
     *                               &lt;simpleType>
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                   &lt;maxLength value="20"/>
     *                                 &lt;/restriction>
     *                               &lt;/simpleType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;choice>
     *                     &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                     &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                   &lt;/choice>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoCuenta",
        "apertura",
        "movimientos"
    })
    public static class Cuenta {

        @XmlElement(name = "CodigoCuenta", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String codigoCuenta;
        @XmlElement(name = "Apertura")
        protected LceMayor.Cuenta.Apertura apertura;
        @XmlElement(name = "Movimientos")
        protected List<LceMayor.Cuenta.Movimientos> movimientos;

        /**
         * Gets the value of the codigoCuenta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCodigoCuenta() {
            return codigoCuenta;
        }

        /**
         * Sets the value of the codigoCuenta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCodigoCuenta(String value) {
            this.codigoCuenta = value;
        }

        /**
         * Gets the value of the apertura property.
         * 
         * @return
         *     possible object is
         *     {@link LceMayor.Cuenta.Apertura }
         *     
         */
        public LceMayor.Cuenta.Apertura getApertura() {
            return apertura;
        }

        /**
         * Sets the value of the apertura property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceMayor.Cuenta.Apertura }
         *     
         */
        public void setApertura(LceMayor.Cuenta.Apertura value) {
            this.apertura = value;
        }

        /**
         * Gets the value of the movimientos property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the movimientos property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMovimientos().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LceMayor.Cuenta.Movimientos }
         * 
         * 
         */
        public List<LceMayor.Cuenta.Movimientos> getMovimientos() {
            if (movimientos == null) {
                movimientos = new ArrayList<LceMayor.Cuenta.Movimientos>();
            }
            return this.movimientos;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *         &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *         &lt;choice>
         *           &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *           &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "debe",
            "haber",
            "saldoDeudor",
            "saldoAcreedor"
        })
        public static class Apertura {

            @XmlElement(name = "Debe")
            protected BigDecimal debe;
            @XmlElement(name = "Haber")
            protected BigDecimal haber;
            @XmlElement(name = "SaldoDeudor")
            protected BigDecimal saldoDeudor;
            @XmlElement(name = "SaldoAcreedor")
            protected BigDecimal saldoAcreedor;

            /**
             * Gets the value of the debe property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDebe() {
                return debe;
            }

            /**
             * Sets the value of the debe property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDebe(BigDecimal value) {
                this.debe = value;
            }

            /**
             * Gets the value of the haber property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getHaber() {
                return haber;
            }

            /**
             * Sets the value of the haber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setHaber(BigDecimal value) {
                this.haber = value;
            }

            /**
             * Gets the value of the saldoDeudor property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSaldoDeudor() {
                return saldoDeudor;
            }

            /**
             * Sets the value of the saldoDeudor property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSaldoDeudor(BigDecimal value) {
                this.saldoDeudor = value;
            }

            /**
             * Gets the value of the saldoAcreedor property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getSaldoAcreedor() {
                return saldoAcreedor;
            }

            /**
             * Sets the value of the saldoAcreedor property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setSaldoAcreedor(BigDecimal value) {
                this.saldoAcreedor = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TpoComp">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;maxLength value="4"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="NumComp">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="18"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="FechaContable" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="GlosaAnalisis" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="120"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Rut" type="{http://www.sii.cl/SiiLce}RUTType" minOccurs="0"/>
         *         &lt;element name="Nombre" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="120"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="TpoDocum" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;maxLength value="15"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Numero" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;maxLength value="18"/>
         *               &lt;minLength value="1"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="FchEmision" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="FchVencimiento" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
         *         &lt;element name="GlosaRef" maxOccurs="4" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Glosa">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="30"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                   &lt;element name="Ref">
         *                     &lt;simpleType>
         *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                         &lt;maxLength value="20"/>
         *                       &lt;/restriction>
         *                     &lt;/simpleType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;choice>
         *           &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *           &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *         &lt;/choice>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "tpoComp",
            "numComp",
            "fechaContable",
            "glosaAnalisis",
            "rut",
            "nombre",
            "tpoDocum",
            "numero",
            "fchEmision",
            "fchVencimiento",
            "glosaRef",
            "debe",
            "haber"
        })
        public static class Movimientos {

            @XmlElement(name = "TpoComp", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String tpoComp;
            @XmlElement(name = "NumComp", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String numComp;
            @XmlElement(name = "FechaContable", required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaContable;
            @XmlElement(name = "GlosaAnalisis")
            protected String glosaAnalisis;
            @XmlElement(name = "Rut")
            protected String rut;
            @XmlElement(name = "Nombre")
            protected String nombre;
            @XmlElement(name = "TpoDocum")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String tpoDocum;
            @XmlElement(name = "Numero")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String numero;
            @XmlElement(name = "FchEmision")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fchEmision;
            @XmlElement(name = "FchVencimiento")
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fchVencimiento;
            @XmlElement(name = "GlosaRef")
            protected List<LceMayor.Cuenta.Movimientos.GlosaRef> glosaRef;
            @XmlElement(name = "Debe")
            protected BigDecimal debe;
            @XmlElement(name = "Haber")
            protected BigDecimal haber;

            /**
             * Gets the value of the tpoComp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTpoComp() {
                return tpoComp;
            }

            /**
             * Sets the value of the tpoComp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTpoComp(String value) {
                this.tpoComp = value;
            }

            /**
             * Gets the value of the numComp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumComp() {
                return numComp;
            }

            /**
             * Sets the value of the numComp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumComp(String value) {
                this.numComp = value;
            }

            /**
             * Gets the value of the fechaContable property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFechaContable() {
                return fechaContable;
            }

            /**
             * Sets the value of the fechaContable property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFechaContable(XMLGregorianCalendar value) {
                this.fechaContable = value;
            }

            /**
             * Gets the value of the glosaAnalisis property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGlosaAnalisis() {
                return glosaAnalisis;
            }

            /**
             * Sets the value of the glosaAnalisis property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGlosaAnalisis(String value) {
                this.glosaAnalisis = value;
            }

            /**
             * Gets the value of the rut property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRut() {
                return rut;
            }

            /**
             * Sets the value of the rut property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRut(String value) {
                this.rut = value;
            }

            /**
             * Gets the value of the nombre property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNombre() {
                return nombre;
            }

            /**
             * Sets the value of the nombre property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNombre(String value) {
                this.nombre = value;
            }

            /**
             * Gets the value of the tpoDocum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTpoDocum() {
                return tpoDocum;
            }

            /**
             * Sets the value of the tpoDocum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTpoDocum(String value) {
                this.tpoDocum = value;
            }

            /**
             * Gets the value of the numero property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumero() {
                return numero;
            }

            /**
             * Sets the value of the numero property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumero(String value) {
                this.numero = value;
            }

            /**
             * Gets the value of the fchEmision property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFchEmision() {
                return fchEmision;
            }

            /**
             * Sets the value of the fchEmision property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFchEmision(XMLGregorianCalendar value) {
                this.fchEmision = value;
            }

            /**
             * Gets the value of the fchVencimiento property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getFchVencimiento() {
                return fchVencimiento;
            }

            /**
             * Sets the value of the fchVencimiento property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setFchVencimiento(XMLGregorianCalendar value) {
                this.fchVencimiento = value;
            }

            /**
             * Gets the value of the glosaRef property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the glosaRef property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGlosaRef().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link LceMayor.Cuenta.Movimientos.GlosaRef }
             * 
             * 
             */
            public List<LceMayor.Cuenta.Movimientos.GlosaRef> getGlosaRef() {
                if (glosaRef == null) {
                    glosaRef = new ArrayList<LceMayor.Cuenta.Movimientos.GlosaRef>();
                }
                return this.glosaRef;
            }

            /**
             * Gets the value of the debe property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getDebe() {
                return debe;
            }

            /**
             * Sets the value of the debe property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setDebe(BigDecimal value) {
                this.debe = value;
            }

            /**
             * Gets the value of the haber property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getHaber() {
                return haber;
            }

            /**
             * Sets the value of the haber property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setHaber(BigDecimal value) {
                this.haber = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Glosa">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="30"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *         &lt;element name="Ref">
             *           &lt;simpleType>
             *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *               &lt;maxLength value="20"/>
             *             &lt;/restriction>
             *           &lt;/simpleType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "glosa",
                "ref"
            })
            public static class GlosaRef {

                @XmlElement(name = "Glosa", required = true)
                protected String glosa;
                @XmlElement(name = "Ref", required = true)
                protected String ref;

                /**
                 * Gets the value of the glosa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGlosa() {
                    return glosa;
                }

                /**
                 * Sets the value of the glosa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGlosa(String value) {
                    this.glosa = value;
                }

                /**
                 * Gets the value of the ref property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRef() {
                    return ref;
                }

                /**
                 * Sets the value of the ref property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRef(String value) {
                    this.ref = value;
                }

            }

        }

    }

}
