//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3._2000._09.xmldsig_.SignatureType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DocumentoMayorRes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Identificacion">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                             &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
 *                             &lt;element name="Moneda" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Cuenta" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="CodigoCuenta">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="20"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="CantidadMovimientos">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
 *                                   &lt;totalDigits value="10"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Cierre">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MontosPeriodo" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                                                 &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                                                 &lt;choice>
 *                                                   &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                                                   &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                                                 &lt;/choice>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="MontosAcumulado">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                                                 &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
 *                                                 &lt;choice>
 *                                                   &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                                                   &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
 *                                                 &lt;/choice>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
 *                   &lt;element name="TmstFirma">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentoMayorRes",
    "signature"
})
@XmlRootElement(name = "LceMayorRes")
public class LceMayorRes {

    @XmlElement(name = "DocumentoMayorRes", required = true)
    protected LceMayorRes.DocumentoMayorRes documentoMayorRes;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(required = true)
    protected BigDecimal version;

    /**
     * Gets the value of the documentoMayorRes property.
     * 
     * @return
     *     possible object is
     *     {@link LceMayorRes.DocumentoMayorRes }
     *     
     */
    public LceMayorRes.DocumentoMayorRes getDocumentoMayorRes() {
        return documentoMayorRes;
    }

    /**
     * Sets the value of the documentoMayorRes property.
     * 
     * @param value
     *     allowed object is
     *     {@link LceMayorRes.DocumentoMayorRes }
     *     
     */
    public void setDocumentoMayorRes(LceMayorRes.DocumentoMayorRes value) {
        this.documentoMayorRes = value;
    }

    /**
     * Firma Digital del Envio del Libro Electronico
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Identificacion">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *                   &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
     *                   &lt;element name="Moneda" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Cuenta" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="CodigoCuenta">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="20"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="CantidadMovimientos">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
     *                         &lt;totalDigits value="10"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Cierre">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="MontosPeriodo" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                                       &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                                       &lt;choice>
     *                                         &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                                         &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                                       &lt;/choice>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="MontosAcumulado">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                                       &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
     *                                       &lt;choice>
     *                                         &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                                         &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
     *                                       &lt;/choice>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="RutFirma" type="{http://www.sii.cl/SiiLce}RUTType"/>
     *         &lt;element name="TmstFirma">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}dateTime">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "identificacion",
        "cuenta",
        "rutFirma",
        "tmstFirma"
    })
    public static class DocumentoMayorRes {

        @XmlElement(name = "Identificacion", required = true)
        protected LceMayorRes.DocumentoMayorRes.Identificacion identificacion;
        @XmlElement(name = "Cuenta", required = true)
        protected List<LceMayorRes.DocumentoMayorRes.Cuenta> cuenta;
        @XmlElement(name = "RutFirma", required = true)
        protected String rutFirma;
        @XmlElement(name = "TmstFirma", required = true)
        protected XMLGregorianCalendar tmstFirma;
        @XmlAttribute(name = "ID", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the identificacion property.
         * 
         * @return
         *     possible object is
         *     {@link LceMayorRes.DocumentoMayorRes.Identificacion }
         *     
         */
        public LceMayorRes.DocumentoMayorRes.Identificacion getIdentificacion() {
            return identificacion;
        }

        /**
         * Sets the value of the identificacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link LceMayorRes.DocumentoMayorRes.Identificacion }
         *     
         */
        public void setIdentificacion(LceMayorRes.DocumentoMayorRes.Identificacion value) {
            this.identificacion = value;
        }

        /**
         * Gets the value of the cuenta property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cuenta property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCuenta().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LceMayorRes.DocumentoMayorRes.Cuenta }
         * 
         * 
         */
        public List<LceMayorRes.DocumentoMayorRes.Cuenta> getCuenta() {
            if (cuenta == null) {
                cuenta = new ArrayList<LceMayorRes.DocumentoMayorRes.Cuenta>();
            }
            return this.cuenta;
        }

        /**
         * Gets the value of the rutFirma property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRutFirma() {
            return rutFirma;
        }

        /**
         * Sets the value of the rutFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRutFirma(String value) {
            this.rutFirma = value;
        }

        /**
         * Gets the value of the tmstFirma property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getTmstFirma() {
            return tmstFirma;
        }

        /**
         * Sets the value of the tmstFirma property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setTmstFirma(XMLGregorianCalendar value) {
            this.tmstFirma = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getID() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setID(String value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="CodigoCuenta">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="20"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="CantidadMovimientos">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger">
         *               &lt;totalDigits value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Cierre">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="MontosPeriodo" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *                             &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *                             &lt;choice>
         *                               &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *                               &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *                             &lt;/choice>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="MontosAcumulado">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *                             &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
         *                             &lt;choice>
         *                               &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *                               &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
         *                             &lt;/choice>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "codigoCuenta",
            "cantidadMovimientos",
            "cierre"
        })
        public static class Cuenta {

            @XmlElement(name = "CodigoCuenta", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String codigoCuenta;
            @XmlElement(name = "CantidadMovimientos", required = true)
            protected BigInteger cantidadMovimientos;
            @XmlElement(name = "Cierre", required = true)
            protected LceMayorRes.DocumentoMayorRes.Cuenta.Cierre cierre;

            /**
             * Gets the value of the codigoCuenta property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCodigoCuenta() {
                return codigoCuenta;
            }

            /**
             * Sets the value of the codigoCuenta property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCodigoCuenta(String value) {
                this.codigoCuenta = value;
            }

            /**
             * Gets the value of the cantidadMovimientos property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getCantidadMovimientos() {
                return cantidadMovimientos;
            }

            /**
             * Sets the value of the cantidadMovimientos property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setCantidadMovimientos(BigInteger value) {
                this.cantidadMovimientos = value;
            }

            /**
             * Gets the value of the cierre property.
             * 
             * @return
             *     possible object is
             *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre }
             *     
             */
            public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre getCierre() {
                return cierre;
            }

            /**
             * Sets the value of the cierre property.
             * 
             * @param value
             *     allowed object is
             *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre }
             *     
             */
            public void setCierre(LceMayorRes.DocumentoMayorRes.Cuenta.Cierre value) {
                this.cierre = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="MontosPeriodo" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
             *                   &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
             *                   &lt;choice>
             *                     &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
             *                     &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
             *                   &lt;/choice>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="MontosAcumulado">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
             *                   &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
             *                   &lt;choice>
             *                     &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
             *                     &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
             *                   &lt;/choice>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "montosPeriodo",
                "montosAcumulado"
            })
            public static class Cierre {

                @XmlElement(name = "MontosPeriodo")
                protected LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo montosPeriodo;
                @XmlElement(name = "MontosAcumulado", required = true)
                protected LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado montosAcumulado;

                /**
                 * Gets the value of the montosPeriodo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo }
                 *     
                 */
                public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo getMontosPeriodo() {
                    return montosPeriodo;
                }

                /**
                 * Sets the value of the montosPeriodo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo }
                 *     
                 */
                public void setMontosPeriodo(LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo value) {
                    this.montosPeriodo = value;
                }

                /**
                 * Gets the value of the montosAcumulado property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado }
                 *     
                 */
                public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado getMontosAcumulado() {
                    return montosAcumulado;
                }

                /**
                 * Sets the value of the montosAcumulado property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado }
                 *     
                 */
                public void setMontosAcumulado(LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado value) {
                    this.montosAcumulado = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
                 *         &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
                 *         &lt;choice>
                 *           &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
                 *           &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
                 *         &lt;/choice>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "debe",
                    "haber",
                    "saldoDeudor",
                    "saldoAcreedor"
                })
                public static class MontosAcumulado {

                    @XmlElement(name = "Debe")
                    protected BigDecimal debe;
                    @XmlElement(name = "Haber")
                    protected BigDecimal haber;
                    @XmlElement(name = "SaldoDeudor")
                    protected BigDecimal saldoDeudor;
                    @XmlElement(name = "SaldoAcreedor")
                    protected BigDecimal saldoAcreedor;

                    /**
                     * Gets the value of the debe property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getDebe() {
                        return debe;
                    }

                    /**
                     * Sets the value of the debe property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setDebe(BigDecimal value) {
                        this.debe = value;
                    }

                    /**
                     * Gets the value of the haber property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getHaber() {
                        return haber;
                    }

                    /**
                     * Sets the value of the haber property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setHaber(BigDecimal value) {
                        this.haber = value;
                    }

                    /**
                     * Gets the value of the saldoDeudor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getSaldoDeudor() {
                        return saldoDeudor;
                    }

                    /**
                     * Sets the value of the saldoDeudor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setSaldoDeudor(BigDecimal value) {
                        this.saldoDeudor = value;
                    }

                    /**
                     * Gets the value of the saldoAcreedor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getSaldoAcreedor() {
                        return saldoAcreedor;
                    }

                    /**
                     * Sets the value of the saldoAcreedor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setSaldoAcreedor(BigDecimal value) {
                        this.saldoAcreedor = value;
                    }

                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Debe" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
                 *         &lt;element name="Haber" type="{http://www.sii.cl/SiiLce}MontoType" minOccurs="0"/>
                 *         &lt;choice>
                 *           &lt;element name="SaldoDeudor" type="{http://www.sii.cl/SiiLce}MontoType"/>
                 *           &lt;element name="SaldoAcreedor" type="{http://www.sii.cl/SiiLce}MontoType"/>
                 *         &lt;/choice>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "debe",
                    "haber",
                    "saldoDeudor",
                    "saldoAcreedor"
                })
                public static class MontosPeriodo {

                    @XmlElement(name = "Debe")
                    protected BigDecimal debe;
                    @XmlElement(name = "Haber")
                    protected BigDecimal haber;
                    @XmlElement(name = "SaldoDeudor")
                    protected BigDecimal saldoDeudor;
                    @XmlElement(name = "SaldoAcreedor")
                    protected BigDecimal saldoAcreedor;

                    /**
                     * Gets the value of the debe property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getDebe() {
                        return debe;
                    }

                    /**
                     * Sets the value of the debe property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setDebe(BigDecimal value) {
                        this.debe = value;
                    }

                    /**
                     * Gets the value of the haber property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getHaber() {
                        return haber;
                    }

                    /**
                     * Sets the value of the haber property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setHaber(BigDecimal value) {
                        this.haber = value;
                    }

                    /**
                     * Gets the value of the saldoDeudor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getSaldoDeudor() {
                        return saldoDeudor;
                    }

                    /**
                     * Sets the value of the saldoDeudor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setSaldoDeudor(BigDecimal value) {
                        this.saldoDeudor = value;
                    }

                    /**
                     * Gets the value of the saldoAcreedor property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getSaldoAcreedor() {
                        return saldoAcreedor;
                    }

                    /**
                     * Sets the value of the saldoAcreedor property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setSaldoAcreedor(BigDecimal value) {
                        this.saldoAcreedor = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RutContribuyente" type="{http://www.sii.cl/SiiLce}RUTType"/>
         *         &lt;element name="PeriodoTributario" type="{http://www.sii.cl/SiiLce}Periodo"/>
         *         &lt;element name="Moneda" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="10"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Rectificatoria" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rutContribuyente",
            "periodoTributario",
            "moneda",
            "rectificatoria"
        })
        public static class Identificacion {

            @XmlElement(name = "RutContribuyente", required = true)
            protected String rutContribuyente;
            @XmlElement(name = "PeriodoTributario", required = true)
            protected Periodo periodoTributario;
            @XmlElement(name = "Moneda")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String moneda;
            @XmlElement(name = "Rectificatoria")
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger rectificatoria;

            /**
             * Gets the value of the rutContribuyente property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRutContribuyente() {
                return rutContribuyente;
            }

            /**
             * Sets the value of the rutContribuyente property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRutContribuyente(String value) {
                this.rutContribuyente = value;
            }

            /**
             * Gets the value of the periodoTributario property.
             * 
             * @return
             *     possible object is
             *     {@link Periodo }
             *     
             */
            public Periodo getPeriodoTributario() {
                return periodoTributario;
            }

            /**
             * Sets the value of the periodoTributario property.
             * 
             * @param value
             *     allowed object is
             *     {@link Periodo }
             *     
             */
            public void setPeriodoTributario(Periodo value) {
                this.periodoTributario = value;
            }

            /**
             * Gets the value of the moneda property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMoneda() {
                return moneda;
            }

            /**
             * Sets the value of the moneda property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMoneda(String value) {
                this.moneda = value;
            }

            /**
             * Gets the value of the rectificatoria property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRectificatoria() {
                return rectificatoria;
            }

            /**
             * Sets the value of the rectificatoria property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRectificatoria(BigInteger value) {
                this.rectificatoria = value;
            }

        }

    }

}
