//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package cl.sii.siilce;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.sii.siilce package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.sii.siilce
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LceDiarioRes }
     * 
     */
    public LceDiarioRes createLceDiarioRes() {
        return new LceDiarioRes();
    }

    /**
     * Create an instance of {@link LceDiarioRes.DocumentoDiarioRes }
     * 
     */
    public LceDiarioRes.DocumentoDiarioRes createLceDiarioResDocumentoDiarioRes() {
        return new LceDiarioRes.DocumentoDiarioRes();
    }

    /**
     * Create an instance of {@link LceDiarioRes.DocumentoDiarioRes.Identificacion }
     * 
     */
    public LceDiarioRes.DocumentoDiarioRes.Identificacion createLceDiarioResDocumentoDiarioResIdentificacion() {
        return new LceDiarioRes.DocumentoDiarioRes.Identificacion();
    }

    /**
     * Create an instance of {@link LceEnvioLibros.DocumentoEnvioLibros.Notificacion }
     * 
     */
    public LceEnvioLibros.DocumentoEnvioLibros.Notificacion createLceEnvioLibrosDocumentoEnvioLibrosNotificacion() {
        return new LceEnvioLibros.DocumentoEnvioLibros.Notificacion();
    }

    /**
     * Create an instance of {@link LceBalance }
     * 
     */
    public LceBalance createLceBalance() {
        return new LceBalance();
    }

    /**
     * Create an instance of {@link Periodo }
     * 
     */
    public Periodo createPeriodo() {
        return new Periodo();
    }

    /**
     * Create an instance of {@link LceDiario.Comprobante.Movimientos }
     * 
     */
    public LceDiario.Comprobante.Movimientos createLceDiarioComprobanteMovimientos() {
        return new LceDiario.Comprobante.Movimientos();
    }

    /**
     * Create an instance of {@link LceDiccionario.DocumentoDiccionario.Identificacion }
     * 
     */
    public LceDiccionario.DocumentoDiccionario.Identificacion createLceDiccionarioDocumentoDiccionarioIdentificacion() {
        return new LceDiccionario.DocumentoDiccionario.Identificacion();
    }

    /**
     * Create an instance of {@link LceDiario }
     * 
     */
    public LceDiario createLceDiario() {
        return new LceDiario();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes }
     * 
     */
    public LceMayorRes.DocumentoMayorRes createLceMayorResDocumentoMayorRes() {
        return new LceMayorRes.DocumentoMayorRes();
    }

    /**
     * Create an instance of {@link LceBalance.DocumentoBalance.Identificacion }
     * 
     */
    public LceBalance.DocumentoBalance.Identificacion createLceBalanceDocumentoBalanceIdentificacion() {
        return new LceBalance.DocumentoBalance.Identificacion();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado }
     * 
     */
    public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado createLceMayorResDocumentoMayorResCuentaCierreMontosAcumulado() {
        return new LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosAcumulado();
    }

    /**
     * Create an instance of {@link LceDiccionario.DocumentoDiccionario }
     * 
     */
    public LceDiccionario.DocumentoDiccionario createLceDiccionarioDocumentoDiccionario() {
        return new LceDiccionario.DocumentoDiccionario();
    }

    /**
     * Create an instance of {@link LceEnvioLibros }
     * 
     */
    public LceEnvioLibros createLceEnvioLibros() {
        return new LceEnvioLibros();
    }

    /**
     * Create an instance of {@link LceMayorRes }
     * 
     */
    public LceMayorRes createLceMayorRes() {
        return new LceMayorRes();
    }

    /**
     * Create an instance of {@link LceMayor.Cuenta.Apertura }
     * 
     */
    public LceMayor.Cuenta.Apertura createLceMayorCuentaApertura() {
        return new LceMayor.Cuenta.Apertura();
    }

    /**
     * Create an instance of {@link LceCal.DocumentoCal }
     * 
     */
    public LceCal.DocumentoCal createLceCalDocumentoCal() {
        return new LceCal.DocumentoCal();
    }

    /**
     * Create an instance of {@link LceDiarioRes.DocumentoDiarioRes.RegistroDiario }
     * 
     */
    public LceDiarioRes.DocumentoDiarioRes.RegistroDiario createLceDiarioResDocumentoDiarioResRegistroDiario() {
        return new LceDiarioRes.DocumentoDiarioRes.RegistroDiario();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo }
     * 
     */
    public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo createLceMayorResDocumentoMayorResCuentaCierreMontosPeriodo() {
        return new LceMayorRes.DocumentoMayorRes.Cuenta.Cierre.MontosPeriodo();
    }

    /**
     * Create an instance of {@link LceDiccionario.DocumentoDiccionario.Cuenta }
     * 
     */
    public LceDiccionario.DocumentoDiccionario.Cuenta createLceDiccionarioDocumentoDiccionarioCuenta() {
        return new LceDiccionario.DocumentoDiccionario.Cuenta();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes.Cuenta.Cierre }
     * 
     */
    public LceMayorRes.DocumentoMayorRes.Cuenta.Cierre createLceMayorResDocumentoMayorResCuentaCierre() {
        return new LceMayorRes.DocumentoMayorRes.Cuenta.Cierre();
    }

    /**
     * Create an instance of {@link LceCoCertif.DocumentoCoCertif }
     * 
     */
    public LceCoCertif.DocumentoCoCertif createLceCoCertifDocumentoCoCertif() {
        return new LceCoCertif.DocumentoCoCertif();
    }

    /**
     * Create an instance of {@link LceDiario.Comprobante }
     * 
     */
    public LceDiario.Comprobante createLceDiarioComprobante() {
        return new LceDiario.Comprobante();
    }

    /**
     * Create an instance of {@link LceMayor }
     * 
     */
    public LceMayor createLceMayor() {
        return new LceMayor();
    }

    /**
     * Create an instance of {@link LceDiarioRes.DocumentoDiarioRes.Cierre }
     * 
     */
    public LceDiarioRes.DocumentoDiarioRes.Cierre createLceDiarioResDocumentoDiarioResCierre() {
        return new LceDiarioRes.DocumentoDiarioRes.Cierre();
    }

    /**
     * Create an instance of {@link LceCal }
     * 
     */
    public LceCal createLceCal() {
        return new LceCal();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes.Identificacion }
     * 
     */
    public LceMayorRes.DocumentoMayorRes.Identificacion createLceMayorResDocumentoMayorResIdentificacion() {
        return new LceMayorRes.DocumentoMayorRes.Identificacion();
    }

    /**
     * Create an instance of {@link LceBalance.DocumentoBalance }
     * 
     */
    public LceBalance.DocumentoBalance createLceBalanceDocumentoBalance() {
        return new LceBalance.DocumentoBalance();
    }

    /**
     * Create an instance of {@link LceMayorRes.DocumentoMayorRes.Cuenta }
     * 
     */
    public LceMayorRes.DocumentoMayorRes.Cuenta createLceMayorResDocumentoMayorResCuenta() {
        return new LceMayorRes.DocumentoMayorRes.Cuenta();
    }

    /**
     * Create an instance of {@link LceDiario.Comprobante.Movimientos.GlosaRef }
     * 
     */
    public LceDiario.Comprobante.Movimientos.GlosaRef createLceDiarioComprobanteMovimientosGlosaRef() {
        return new LceDiario.Comprobante.Movimientos.GlosaRef();
    }

    /**
     * Create an instance of {@link LceMayor.Cuenta.Movimientos.GlosaRef }
     * 
     */
    public LceMayor.Cuenta.Movimientos.GlosaRef createLceMayorCuentaMovimientosGlosaRef() {
        return new LceMayor.Cuenta.Movimientos.GlosaRef();
    }

    /**
     * Create an instance of {@link LceDiccionario }
     * 
     */
    public LceDiccionario createLceDiccionario() {
        return new LceDiccionario();
    }

    /**
     * Create an instance of {@link LceCoCertif }
     * 
     */
    public LceCoCertif createLceCoCertif() {
        return new LceCoCertif();
    }

    /**
     * Create an instance of {@link LceMayor.Cuenta.Movimientos }
     * 
     */
    public LceMayor.Cuenta.Movimientos createLceMayorCuentaMovimientos() {
        return new LceMayor.Cuenta.Movimientos();
    }

    /**
     * Create an instance of {@link LceEnvioLibros.LCE.NoCerrado }
     * 
     */
    public LceEnvioLibros.LCE.NoCerrado createLceEnvioLibrosLCENoCerrado() {
        return new LceEnvioLibros.LCE.NoCerrado();
    }

    /**
     * Create an instance of {@link LceEnvioLibros.DocumentoEnvioLibros }
     * 
     */
    public LceEnvioLibros.DocumentoEnvioLibros createLceEnvioLibrosDocumentoEnvioLibros() {
        return new LceEnvioLibros.DocumentoEnvioLibros();
    }

    /**
     * Create an instance of {@link LceBalance.DocumentoBalance.Cuenta }
     * 
     */
    public LceBalance.DocumentoBalance.Cuenta createLceBalanceDocumentoBalanceCuenta() {
        return new LceBalance.DocumentoBalance.Cuenta();
    }

    /**
     * Create an instance of {@link LceEnvioLibros.LCE }
     * 
     */
    public LceEnvioLibros.LCE createLceEnvioLibrosLCE() {
        return new LceEnvioLibros.LCE();
    }

    /**
     * Create an instance of {@link LceMayor.Cuenta }
     * 
     */
    public LceMayor.Cuenta createLceMayorCuenta() {
        return new LceMayor.Cuenta();
    }

}
