//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.24 at 09:18:21 PM CLST 
//


package org.w3._2000._09.xmldsig_;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.w3._2000._09.xmldsig_ package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.w3._2000._09.xmldsig_
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.RSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.RSAKeyValue createSignatureTypeKeyInfoKeyValueRSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.RSAKeyValue();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.DigestMethod }
     * 
     */
    public SignatureType.SignedInfo.Reference.DigestMethod createSignatureTypeSignedInfoReferenceDigestMethod() {
        return new SignatureType.SignedInfo.Reference.DigestMethod();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo }
     * 
     */
    public SignatureType.KeyInfo createSignatureTypeKeyInfo() {
        return new SignatureType.KeyInfo();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms.Transform }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms.Transform createSignatureTypeSignedInfoReferenceTransformsTransform() {
        return new SignatureType.SignedInfo.Reference.Transforms.Transform();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.X509Data }
     * 
     */
    public SignatureType.KeyInfo.X509Data createSignatureTypeKeyInfoX509Data() {
        return new SignatureType.KeyInfo.X509Data();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.SignatureMethod }
     * 
     */
    public SignatureType.SignedInfo.SignatureMethod createSignatureTypeSignedInfoSignatureMethod() {
        return new SignatureType.SignedInfo.SignatureMethod();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference }
     * 
     */
    public SignatureType.SignedInfo.Reference createSignatureTypeSignedInfoReference() {
        return new SignatureType.SignedInfo.Reference();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue createSignatureTypeKeyInfoKeyValue() {
        return new SignatureType.KeyInfo.KeyValue();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo }
     * 
     */
    public SignatureType.SignedInfo createSignatureTypeSignedInfo() {
        return new SignatureType.SignedInfo();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.Reference.Transforms }
     * 
     */
    public SignatureType.SignedInfo.Reference.Transforms createSignatureTypeSignedInfoReferenceTransforms() {
        return new SignatureType.SignedInfo.Reference.Transforms();
    }

    /**
     * Create an instance of {@link SignatureType.SignedInfo.CanonicalizationMethod }
     * 
     */
    public SignatureType.SignedInfo.CanonicalizationMethod createSignatureTypeSignedInfoCanonicalizationMethod() {
        return new SignatureType.SignedInfo.CanonicalizationMethod();
    }

    /**
     * Create an instance of {@link SignatureType.KeyInfo.KeyValue.DSAKeyValue }
     * 
     */
    public SignatureType.KeyInfo.KeyValue.DSAKeyValue createSignatureTypeKeyInfoKeyValueDSAKeyValue() {
        return new SignatureType.KeyInfo.KeyValue.DSAKeyValue();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

}
